//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.Ticketing.Win {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OTS.Ticketing.Win.messages-ar", typeof(messages_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إغلاق البطاقة.
        /// </summary>
        internal static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشركة.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متأكد من إغلاق البرنامج ؟.
        /// </summary>
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإغلاق.
        /// </summary>
        internal static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب الملفات.
        /// </summary>
        internal static string IsIndexed {
            get {
                return ResourceManager.GetString("IsIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البطاقة.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تشغيل البرنامج أكثر من مرة !!.
        /// </summary>
        internal static string OneTimeProgramRunning {
            get {
                return ResourceManager.GetString("OneTimeProgramRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ فتح البطاقة.
        /// </summary>
        internal static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشكلة.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعة البطاقة.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرنامج.
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هلو.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحويل الى.
        /// </summary>
        internal static string TransferedTo {
            get {
                return ResourceManager.GetString("TransferedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التأكد من معلومات الدخول !.
        /// </summary>
        internal static string WrongInformations {
            get {
                return ResourceManager.GetString("WrongInformations", resourceCulture);
            }
        }
    }
}
